# Number of days of inactivity before an issue becomes stale
daysUntilStale: 61
# Number of days of inactivity before a stale issue is closed
daysUntilClose: 14
# Issues with these labels will never be considered stale
exemptLabels:
  - Bug
  - Crash
  - pinned
  - Visual
# Label to use when marking an issue as stale
staleLabel: noactivity
# Comment to post when marking an issue as stale. Set to `false` to disable
markComment: >
  This issue hasn't been updated in over 60 days. It has been marked as 'stale' and will be closed in 14 days. Please check whether this is still an issue with the latest version of Quicksilver. If so, update or comment on this issue to keep it open.
# Comment to post when closing a stale issue. Set to `false` to disable
closeComment: false

# Limit to only `issues` or `pulls`
only: issues

# Limit the number of actions per hour, from 1-30. Default is 30
limitPerRun: 30
