[package]
name = "{{project-name}}"
version = "0.1.0"
authors = ["Nathan Henrie <nate@n8henrie.com>"]
readme = "README.md"
license = "MIT"
edition = "2021"
description = "{{ project-description }}"
repository = "https://github.com/{{ username }}/{{ repo_name }}"

[dependencies]
