[template]
cargo_generate_version = ">=0.10.0"

[placeholders.repo_name]
type = "string"
prompt = "Repo name?"

[placeholders.project-description]
type = "string"
prompt = "Project description?"

[placeholders.username]
type = "string"
prompt = "GitHub username (or organization)?"
default = "n8henrie"

[placeholders.name]
type = "string"
default = "Nathan Henrie"
prompt = "Author name?"

[placeholders.email]
type = "string"
default = "nate@n8henrie.com"
prompt = "Email?"

[placeholders.year]
type = "string"
default = "2022"
prompt = "Year?"

[conditional.'crate_type == "lib"']
ignore = [ "src/main.rs" ]

[conditional.'crate_type == "bin"']
ignore = [ "src/lib.rs" ]
