[package]
name = "remac"
version = "0.1.0"
authors = ["Nathan Henrie <nate@n8henrie.com>"]
readme = "README.md"
license = "MIT"
edition = "2021"
description = "Change your MAC address"
repository = "https://github.com/n8henrie/remac"

[dependencies]

[lints.clippy]
pedantic = "warn"
