---
name: CD

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
{% if crate_type == "bin" %}
  publish:
    name: Publishing for {% raw %}${{ matrix.job.os  }}{% endraw %}
    runs-on: {% raw %}${{ matrix.job.os }}{% endraw %}
    strategy:
      matrix:
        rust: [stable]
        job:
          - os: macos-latest
            os-name: macos
            target: x86_64-apple-darwin
            architecture: x86_64
            binary-postfix: ""
            use-cross: false
          - os: ubuntu-latest
            os-name: linux
            target: x86_64-unknown-linux-gnu
            architecture: x86_64
            binary-postfix: ""
            use-cross: false
          - os: windows-latest
            os-name: windows
            target: x86_64-pc-windows-msvc
            architecture: x86_64
            binary-postfix: ".exe"
            use-cross: false
          - os: ubuntu-latest
            os-name: linux
            target: aarch64-unknown-linux-gnu
            architecture: arm64
            binary-postfix: ""
            use-cross: true
          - os: ubuntu-latest
            os-name: linux
            target: i686-unknown-linux-gnu
            architecture: i686
            binary-postfix: ""
            use-cross: true

    steps:
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: {% raw %}${{ matrix.rust }}{% endraw %}
          profile: minimal
          override: true
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Cargo build
        uses: actions-rs/cargo@v1
        with:
          command: build
          use-cross: {% raw %}${{ matrix.job.use-cross }}{% endraw %}
          toolchain: {% raw %}${{ matrix.rust }}{% endraw %}
          args: --release --target {% raw %}${{ matrix.job.target }}{% endraw %}

      - name: install strip command
        shell: bash
        run: |
          if [[ "{% raw %}${{ matrix.job.target }}{% endraw %}" == aarch64-unknown-linux-gnu ]]; then
              sudo apt update
              sudo apt-get install -y binutils-aarch64-linux-gnu
          fi
      - name: Packaging final binary
        shell: bash
        run: |
          cd target/"{% raw %}${{ matrix.job.target }}{% endraw %}"/release

          ####### reduce binary size by removing debug symbols #######
          BINARY_NAME="{{project-name}}{% raw %}${{ matrix.job.binary-postfix }}{% endraw %}"
          if [[ "{% raw %}${{ matrix.job.target }}{% endraw %}" == aarch64-unknown-linux-gnu ]]; then
            GCC_PREFIX="aarch64-linux-gnu-"
          else
            GCC_PREFIX=""
          fi
          "$GCC_PREFIX"strip $BINARY_NAME

          ########## create tar.gz ##########
          RELEASE_NAME={{project-name}}-${GITHUB_REF/refs\/tags\//}-{% raw %}"${{ matrix.job.os-name }}-${{ matrix.job.architecture }}"{% endraw %}
          tar czvf $RELEASE_NAME.tar.gz $BINARY_NAME

          ########## create sha256 ##########
          if [[ "{% raw %}${{ runner.os  }}{% endraw %}" == 'Windows' ]]; then
            certutil -hashfile $RELEASE_NAME.tar.gz sha256 | grep -E [A-Fa-f0-9]{64} > $RELEASE_NAME.sha256
          else
            shasum -a 256 $RELEASE_NAME.tar.gz > $RELEASE_NAME.sha256
          fi
      - name: Releasing assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            target/"{% raw %}${{ matrix.job.target }}{% endraw %}"/release/{{project-name}}-*.tar.gz
            target/"{% raw %}${{ matrix.job.target }}{% endraw %}"/release/{{project-name}}-*.sha256
        env:
          GITHUB_TOKEN: {% raw %}${{ secrets.GITHUB_TOKEN }}{% endraw %}
{% endif %}
  publish-cargo:
    name: Publishing to Cargo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo publish --token "{% raw %}${{ secrets.CARGO_API_KEY }}{% endraw %}"
